//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnomediaTestTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assignments()
        {
            this.work_logs = new HashSet<work_logs>();
        }
    
        public int id { get; set; }
        public int team_id { get; set; }
        public int request_id { get; set; }
    
        public virtual requests requests { get; set; }
        public virtual teams teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_logs> work_logs { get; set; }
    }
}
