//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnomediaTestTask
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechnomediaTestTaskDBEntities : DbContext
    {
        public TechnomediaTestTaskDBEntities()
            : base("name=TechnomediaTestTaskDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assignments> assignments { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<requests> requests { get; set; }
        public virtual DbSet<teams> teams { get; set; }
        public virtual DbSet<work_logs> work_logs { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
