//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnomediaTestTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requests()
        {
            this.assignments = new HashSet<assignments>();
        }
    
        public int id { get; set; }
        public int client_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string notes { get; set; }
        public string status { get; set; }
        public string research_notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignments> assignments { get; set; }
        public virtual clients clients { get; set; }
    }
}
