//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnomediaTestTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_logs
    {
        public int id { get; set; }
        public int assignment_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string comments { get; set; }
    
        public virtual assignments assignments { get; set; }
    }
}
